fead: requiere revisar y arreglar
4GeeksAcademy/ElisaGDR-ContactList pull request #1
Opened 2023-09-25 16:30 UTC by ElisaGDR

Revisar: 
Botón eliminar/delete 
Crear: 
botón editar/put

2023-09-30 00:41 UTC, hchocobar requested changes
# Review

- Agregué comentarios para cambios en `flux.js` y en `ContactCarc.jsx`
- Además falta habilitar el putUsers en el `ContactCard.jsx` y en `flux.js`

2023-09-30 00:41 UTC, hchocobar commented on src/js/store/flux.js
# Review

## actions postUsers

Adjunto print con los cambios.

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/b5a22fea-1d7f-49f7-b65b-3c3fa389aee9)

## actions putUsers

Adjunto print con los cambios

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/8cea83bb-700c-4b76-b1ed-1bb6db1a6193)

## actions deleteUsers

Adjunto print de pantalla con los cambios

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/c256ef85-fdf8-487c-b49b-4d07f2e6cae8)

2023-09-30 00:41 UTC, hchocobar commented on src/js/views/ContactCard.js
# Review

## Función handleDelete

- Cambios en el onClick del button (trash), cambia la forma de invocarla para enviar el id como parámetro
- Cambios en la defición de la función handleDelete 
  - para recibir el parámetro y 
  - para enviar el id al actions.
  - elimina el getUsers (porque se realiza dentro del actions deleteUsers

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/0b47ce84-19a0-4200-95f5-8c603d8fd3b6)

2023-10-01 19:14 UTC, ElisaGDR commented
He actualizado el código. Delete funciona y Put también. Aunque no se queda actualizado en el componente Contact. Consola dice que es debido a un problema de CORS, que ocurre cuando intentas hacer una solicitud fetch desde un dominio diferente al del servidor. Este problema es común cuando trabajas en un entorno de desarrollo local y estás tratando de acceder a un servidor remoto (la explicación me la ha dado ChatGPT). No estoy segura pero eso ya no se logra actualizando el código me parece. ¿Qué opinas?

2023-10-03 02:03 UTC, hchocobar requested changes

2023-10-03 02:03 UTC, hchocobar commented on src/js/views/EditContact.jsx
# Review

@ElisaGDR , 

## Archivo EditContact.jsx, 

- en la función submitContact, hay dos líneas que se encuentran con sintáxis incorrectas. En la imagen, he comentado las tuyas y escrito las que corresponden.

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/4c997cb9-5cd9-45c1-a987-0e2e30f690e2)

2023-10-03 02:03 UTC, hchocobar commented on src/js/store/flux.js
# Review

## Archivo flux.js

- En la función putUsers, la url del endpoint que definiste es incorrecta. En la imágen la he comentado y en la línea siguiente escribí la que corresponde.

![imagen](https://github.com/4GeeksAcademy/ElisaGDR-ContactList/assets/45291267/4ac2b92a-4821-4274-b23a-7072542812db)

2023-10-03 14:27 UTC, ElisaGDR commented on src/js/store/flux.js
Perfecto Héctor, cambios hechos y funciona a la perfección. Gracias! Procedo al merge.

2023-10-03 14:28 UTC, merged

2023-10-03 21:56 UTC, hchocobar commented on src/js/views/EditContact.jsx
@ElisaGDR 
Viste este cambio ?

2023-10-04 09:14 UTC, ElisaGDR commented
Sí lo había visto. Ya lo modifiqué :)

El mar., 3 oct. 2023 23:57, Héctor Chocobar-Torrejón <
***@***.***> escribió:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On src/js/views/EditContact.jsx
> <https://github.com/4GeeksAcademy/ElisaGDR-ContactList/pull/1#discussion_r1344788527>
> :
>
> @ElisaGDR <https://github.com/ElisaGDR>
> Viste este cambio ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/4GeeksAcademy/ElisaGDR-ContactList/pull/1#discussion_r1344788527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BAHTVYJB577BBZXZRAPUFGTX5SC3LAVCNFSM6AAAAAA5GLTG6GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJWGE4TGNJRGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-04 11:10 UTC, hchocobar reviewed
Genial!!!
Listo!!!